# Generated by Django 5.0.6 on 2024-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paper_summarizer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
