# Generated by Django 5.0.6 on 2024-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paper_summarizer", "0002_user_api_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="api_token",
            new_name="GeminiAPI",
        ),
        migrations.AddField(
            model_name="user",
            name="NotionAPI",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="OpenaiAPI",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
