# Generated by Django 5.0.6 on 2024-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paper_summarizer",
            "0003_rename_api_token_user_geminiapi_user_notionapi_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="NotionDatabaseID",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
